Fix resizepvc alert command, do not mutate the brokerConfigGroups specs
banzaicloud/kafka-operator pull request #451
Opened 2020-09-14 10:31 UTC by baluchicken

| Q               | A
| --------------- | ---
| Bug fix?        |yes|
| New feature?    | no|
| API breaks?     | no|
| Deprecations?   | no|
| License         | Apache 2.0

### What's in this PR?

This PR fixes the resizepvc alert command, since it mutated the brokerConfigGroups as well. It lead to unnecessary updates to unaffected  brokers PV.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [x] User guide and development docs updated (if needed)

### To Do

- [ ] Check alert manager processed feature durability

2020-09-14 11:29 UTC, stoader requested changes

2020-09-14 11:29 UTC, stoader commented on internal/alertmanager/currentalert/process.go
>  					incrementBy, err := resource.ParseQuantity(string(annotiations["incrementBy"]))
Move this to the beginning of the `resizePvc` method instead of re-reading it in every step of the loop

2020-09-14 11:29 UTC, stoader commented on internal/alertmanager/currentalert/process.go
> +					modifiableConfig.PvcSpec.Resources.Requests = corev1.ResourceList{
```suggestion
					modifiableConfig.PvcSpec.Resources.Requests["storage"] = size
```

2020-09-14 11:29 UTC, stoader commented on internal/alertmanager/currentalert/process.go
>  						"storage": size,
```suggestion
```

2020-09-14 11:29 UTC, stoader commented on internal/alertmanager/currentalert/process.go
>  					}
```suggestion
					
```

2020-09-15 10:32 UTC, stoader approved these changes

2020-09-15 10:45 UTC, hi-im-aren approved these changes

2020-09-15 10:47 UTC, merged