Merge the configured and the running broker ids when reconciling services
banzaicloud/kafka-operator pull request #501
Opened 2020-11-18 15:52 UTC by adamantal

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes regression from #457 
| License         | Apache 2.0

### What's in this PR?

Fixes a regression introduced by #457.

Tested locally in docker-desktop.
After specifying external listener config in cold start the reconcile succeeds.

### Why?

See more information at #440.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

2020-11-18 18:05 UTC, stoader requested changes

2020-11-18 18:05 UTC, stoader commented on pkg/util/util.go
> +	brokerIdMap := make(map[int]bool)
```suggestion
	brokerIdMap := make(map[int]struct{})
```

2020-11-18 18:05 UTC, stoader commented on pkg/util/util.go
> +		brokerIdMap[int(broker.Id)] = true
```suggestion
		brokerIdMap[int(broker.Id)] = struct{}{}
```

2020-11-18 18:05 UTC, stoader commented on pkg/util/util.go
> +		brokerIdMap[id] = true
```suggestion
		brokerIdMap[id] = struct{}{}
```

2020-11-18 18:05 UTC, stoader commented on pkg/util/util.go
> +	brokerIds := make([]int, 0)
```suggestion
	brokerIds := make([]int, 0, len(brokerIdMap))
```

2020-11-18 22:05 UTC, amuraru commented
thanks @adamantal for tagging me on https://github.com/banzaicloud/kafka-operator/issues/440#issuecomment-729771482
I am curious is that ingress reconcile succeeds eventually on a fresh start after the first kafka pod is created and a status entry is added?

2020-11-18 22:05 UTC, amuraru commented
/cc @alungu

2020-11-19 09:52 UTC, adamantal commented
> thanks @adamantal for tagging me on [#440 (comment)](https://github.com/banzaicloud/kafka-operator/issues/440#issuecomment-729771482)
> I am curious is that ingress reconcile succeeds eventually on a fresh start after the first kafka pod is created and a status entry is added?

Unfortunately no, the reconcile does not succeed eventually. 
The creation of broker pods happens on a later point in time, so we fail sooner with the error about the bad service spec.

However this does not happen if you have an already running cluster because there are valid broker statuses.

2020-11-19 10:56 UTC, adamantal commented
Added unit tests in latest commit.

2020-11-19 10:56 UTC, stoader approved these changes

2020-11-19 11:00 UTC, baluchicken approved these changes

2020-11-19 11:16 UTC, merged