Add support for multiple listener config per externalListener and brokerIdBindings
banzaicloud/kafka-operator pull request #548
Opened 2021-02-05 10:05 UTC by baluchicken

| Q               | A
| --------------- | ---
| Bug fix?        | no|
| New feature?    |yes|
| API breaks?     | no|
| Deprecations?   | no|
| Related tickets | fixes #487
| License         | Apache 2.0

### What's in this PR?

This PR adds support to provide multiple externalListener configuration. 
With brokerId bindings it can be used to support multi AZ scenarios, where brokers can be bind to specific ingress controller avoiding multi regional traffic. 

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)

### To Do

- [ ] Add IstioIngress related tests

2021-02-05 12:55 UTC, baluchicken commented on pkg/resources/istioingress/gateway.go
> +		brokerConfig, err := util.GetBrokerConfig(kc.Spec.Brokers[brokerId], kc.Spec)
Error here should be fixed.

2021-02-05 12:55 UTC, baluchicken commented on pkg/resources/envoy/service.go
> +		}
This part should be factored out since it is used in many places

2021-02-05 12:57 UTC, baluchicken commented on pkg/resources/istioingress/virtualservice.go
> +		brokerConfig, err := util.GetBrokerConfig(kc.Spec.Brokers[brokerId], kc.Spec)
Error here should be fixed.

2021-02-05 12:57 UTC, baluchicken commented on pkg/resources/istioingress/virtualservice.go
> +		brokerConfig, err := util.GetBrokerConfig(kc.Spec.Brokers[brokerId], kc.Spec)
Error here should be fixed

2021-02-05 13:00 UTC, baluchicken commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	// If left empty, all broker will inherit this loadbalancer
Rephrase this comment.

2021-02-07 06:49 UTC, stoader requested changes

2021-02-07 06:49 UTC, stoader commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	Config *Config `json:"config,omitempty"`
```suggestion
        // +optional
	Config *Config `json:"config,omitempty"`
```

2021-02-07 06:49 UTC, stoader commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	// configuring Config allows to specify ingress controller configuration per external listener
```suggestion
	// Config allows to specify ingress controller configuration per external listener
```

2021-02-07 06:49 UTC, stoader commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	// if not set the default IstioIngressConfig or EnvoyConfig will be used from the KafkaClusterSpec
```suggestion
	// if set overrides the the default `KafkaClusterSpec.IstioIngressConfig` or `KafkaClusterSpec.EnvoyConfig`  for this external listener.
```

2021-02-07 06:49 UTC, stoader commented on pkg/sdk/v1beta1/common_types.go
> +// ExternalListenerConfigNames holds the name of the brokerIdBindings
```suggestion
// ExternalListenerConfigNames type describes a collection of external listener names
```

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/configmap.go
> +	if ingressConfigName == util.IngressConfigGlobalName {
The logic for determining the value for `configMapName` could be factored out into a separate function.

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/configmap.go
> +			labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName), r.KafkaCluster),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/deployment.go
> +			labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/deployment.go
> +				MatchLabels: labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/deployment.go
> +					Labels: labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/service.go
> +			labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/envoy/service.go
> +			Selector:                 labelsForEnvoyIngress(r.KafkaCluster.GetName(), annotationName),
Why `annotationName` is passed into `labelsForEnvoyIngress` instead of `extListener.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/istioingress/gateway.go
> +			Selector: labelsForIstioIngress(r.KafkaCluster.Name, annotationName),
Why `annotationName` is passed into `labelsForIstioIngress` instead of `externalListenerConfig.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/istioingress/meshgateway.go
> +			labelsForIstioIngress(r.KafkaCluster.Name, annotationName), r.KafkaCluster),
Why `annotationName` is passed into `labelsForIstioIngress` instead of `externalListenerConfig.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/istioingress/meshgateway.go
> +				ServiceAnnotations: ingressConfig.GetServiceAnnotations(),
Why `annotationName` is passed into `labelsForIstioIngress` instead of `externalListenerConfig.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/istioingress/virtualservice.go
> +			labelsForIstioIngress(r.KafkaCluster.Name, annotationName),
Why `annotationName` is passed into `labelsForIstioIngress` instead of `externalListenerConfig.Name`?

2021-02-07 06:49 UTC, stoader commented on pkg/resources/istioingress/gateway.go
> +			labelsForIstioIngress(r.KafkaCluster.Name, annotationName), r.KafkaCluster),
Why `annotationName` is passed into `labelsForIstioIngress` instead of `externalListenerConfig.Name`?

2021-02-10 08:42 UTC, stoader requested changes

2021-02-10 08:42 UTC, stoader commented on config/samples/simplekafkacluster-with-brokerbindings.yaml
> +            az1:
```suggestion
            ingress-az1:
```

2021-02-10 08:42 UTC, stoader commented on config/samples/simplekafkacluster-with-brokerbindings.yaml
> +            az2:
```suggestion
            ingress-az2:
```

2021-02-10 08:42 UTC, stoader commented on config/samples/simplekafkacluster-with-brokerbindings.yaml
> +          - "az1"
```suggestion
          - "ingress-az1"
```

2021-02-10 08:42 UTC, stoader commented on config/samples/simplekafkacluster-with-brokerbindings.yaml
> +          - "az1"
```suggestion
          - "ingress-az1"
```

2021-02-10 16:55 UTC, stoader approved these changes

2021-02-12 15:20 UTC, stoader approved these changes

2021-02-12 15:36 UTC, hi-im-aren approved these changes

2021-02-12 15:41 UTC, merged