Add default broker capacity config for CruiseControl
banzaicloud/kafka-operator pull request #556
Opened 2021-02-10 14:03 UTC by adamantal

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | -
| License         | Apache 2.0

### What's in this PR?

Adding a default broker capacity config to the CruiseControl `capacity.json` file.

### Why?

After ungraceful broker deletion the CruiseControl might not be aware of the brokers currently being deleted. Adding a default capacity entry to the capacity json enables CC to handle these brokers (though the actual value of resources does not matter).

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

2021-02-10 14:08 UTC, schultheiszn submitted a review, later dismissed

2021-02-10 14:26 UTC, baluchicken approved these changes

2021-02-10 15:25 UTC, stoader submitted a review, later dismissed

2021-02-12 14:06 UTC, baluchicken approved these changes

2021-02-12 14:27 UTC, stoader requested changes

2021-02-12 14:27 UTC, stoader commented on pkg/resources/cruisecontrol/configmap.go
> +		return ""
log the error

2021-02-12 14:27 UTC, stoader commented on pkg/resources/cruisecontrol/configmap.go
> +func ensureContainsDefaultBrokerCapacity(data string) string {
```suggestion
func ensureContainsDefaultBrokerCapacity(brokerCapacities []byte) []byte {
```

2021-02-12 14:27 UTC, stoader commented on pkg/resources/cruisecontrol/configmap.go
> +		return ""
log the error

2021-02-12 14:27 UTC, stoader commented on pkg/resources/cruisecontrol/configmap.go
> +	return string(result)
```suggestion
	return result
```

2021-02-12 16:23 UTC, stoader approved these changes

2021-02-12 16:29 UTC, baluchicken approved these changes

2021-02-12 16:31 UTC, merged