Introduce new kafka version related status fields
banzaicloud/kafka-operator pull request #596
Opened 2021-04-23 13:06 UTC by baluchicken

| Q               | A
| --------------- | ---
| Bug fix?        | no|
| New feature?    |yes|
| API breaks?     | no|
| Deprecations?   | no|
| License         | Apache 2.0

### What's in this PR?

This PR introduces new kafka version related status fields to the CRD.

2021-04-23 13:29 UTC, stoader commented on pkg/sdk/v1beta1/common_types.go
> +	// KafkaVersion holds the kafka version with the used docker image version
```suggestion
	// KafkaVersion holds the kafka version of the broker in semver format
```

2021-04-23 13:34 UTC, chrisgacsal commented on pkg/sdk/v1beta1/common_types.go
> +	Version        string `json:"version"`
Indentation alert. 🚨

2021-04-23 13:55 UTC, baluchicken commented on pkg/sdk/v1beta1/common_types.go
> +	Version        string `json:"version"`
Thanks

2021-04-26 09:06 UTC, stoader requested changes

2021-04-26 09:06 UTC, stoader commented on pkg/sdk/v1beta1/common_types.go
> +	Version string `json:"version"`
```suggestion
    // Version holds the current version of the broker in semver format
	Version string `json:"version"`
```

2021-04-26 09:06 UTC, stoader commented on pkg/sdk/v1beta1/common_types.go
> +	Image   string `json:"image"`
```suggestion
    // Image specifies the current docker image of the broker 
	Image   string `json:"image"`
```

2021-04-26 09:20 UTC, stoader approved these changes

2021-04-26 09:23 UTC, schultheiszn approved these changes

2021-04-26 09:35 UTC, adamantal approved these changes

2021-04-26 09:36 UTC, merged