Add kafka broker version to status field and update jmx exporter version
banzaicloud/kafka-operator pull request #601
Opened 2021-05-03 16:08 UTC by baluchicken

| Q               | A
| --------------- | ---
| Bug fix?        | no|
| New feature?    |yes|
| API breaks?     | no|
| Deprecations?   | no|
| License         | Apache 2.0

### What's in this PR?

This PR adds broker version to the kafka cluster cr.
It also updates the jmx exporter to version 0.15.0 instead of 0.14.0.
And slightly modifies the jmx exporter config to be able to parse the version properly.

### Checklist

- [X] Implementation tested
- [X] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [X] Logging code meets the guideline
- [X] User guide and development docs updated (if needed)

2021-05-03 16:17 UTC, stoader requested changes

2021-05-03 16:17 UTC, stoader commented on pkg/resources/kafka/kafka.go
> +	jmxMetricRegex := regexp.MustCompile(
This could be made a package level private variable so that the regex is not re-compiled whenever `updateStatusWithDockerImageAndVersion` is invoked.

2021-05-03 16:17 UTC, stoader commented on pkg/resources/kafka/kafka.go
> +			fmt.Sprintf("http://%s-%d."+kafka.HeadlessServiceTemplate+":%d", r.KafkaCluster.GetName(), brokerId, r.KafkaCluster.GetName(), 9020)
Cluster domain and namespace are missing from the URL.

2021-05-03 16:17 UTC, stoader commented on pkg/resources/kafka/kafka.go
> +		requestURL = fmt.Sprintf("http://%s-%d:%d", r.KafkaCluster.GetName(), brokerId, 9020)
Cluster domain and namespace are missing from the URL.

2021-05-05 09:10 UTC, stoader submitted a review, later dismissed

2021-05-05 09:48 UTC, chrisgacsal approved these changes

2021-05-05 12:00 UTC, stoader approved these changes

2021-05-05 12:09 UTC, chrisgacsal approved these changes

2021-05-05 12:52 UTC, merged