Added Resources config for initContainers
banzaicloud/kafka-operator pull request #638
Opened 2021-07-12 13:41 UTC by azun

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #477  |
| License         | Apache 2.0 |

### What's in this PR?
Added initContaninerResourceRequirements to brokerConfig and cruisecontrolConfg

### Why?
When no resource requirements are specified, the broker pod is not Guaranteed for QoS scheduling 

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2021-07-12 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/kafka-operator?pullRequest=638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/kafka-operator?pullRequest=638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/kafka-operator?pullRequest=638) it.</sub>

2021-07-12 13:59 UTC, stoader requested changes

2021-07-12 13:59 UTC, stoader commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	InitContainersResourceRequirements *corev1.ResourceRequirements `json:"initContainersResourceRequirements,omitempty"`
This field is redundant. The `InitContainers []corev1.Container` field already defines resource requirements for each init container.

2021-07-12 14:20 UTC, stoader requested changes

2021-07-12 14:20 UTC, stoader commented on pkg/sdk/v1beta1/kafkacluster_types.go
> +	InitContainersResourceRequirements *corev1.ResourceRequirements `json:"initContainersResourceRequirements,omitempty"`
This field is redundant. The InitContainers []corev1.Container field already defines resource requirements for each init container.

2021-07-13 07:56 UTC, amuraru commented on pkg/resources/kafka/pod.go
> +			Resources: *brokerConfig.InitContainersResourceRequirements,
what we really miss here are the sensible defaults for builtin init containers.
I suggest we provide them statically here inline (via a helper method or so).

As @stoader also correctly pointed out - any additional init container can already provide resource requirements via the `InitContainers` struct.

2021-07-14 08:39 UTC, stoader requested changes

2021-07-14 08:39 UTC, stoader commented on pkg/resources/cruisecontrol/deployment.go
> +func getInitResourcesRequirements() corev1.ResourceRequirements {
Let's move this function to a common place in order to not duplicate it. Also I'd rename it to something like `getDefaultInitContainerResourcesRequirements` as that name better reflects what it is for.

2021-07-19 11:43 UTC, stoader approved these changes

2021-07-19 11:44 UTC, hi-im-aren approved these changes

2021-07-21 05:19 UTC, merged